name: Test Project
on: push
jobs:
    test:
        runs-on: ubuntu-latest # Runner (server)
        steps:
            - name: Get code
              uses: actions/checkout@v5
            - name: Install NodeJS
              uses: actions/setup-node@v5
              with:
                node-version: 'latest'
            - name: Install dependencies
              run: npm ci # install dependencies that are in the package.json file
            - name: Run tests
              run: npm test